swagger: "2.0"
info:
  title: CoBadge Issuers
  description: The issuers can handle the co-badge cards search [see](https://www.pivotaltracker.com/story/show/176575992).
  version: "0.1"
paths:
definitions:
  CoBadgeServices:
    type: object
    additionalProperties:
      $ref: "#/definitions/CoBadgeService"
  CoBadgeService:
    type: object
    required:
      - active
      - issuers
    properties:
      active:
        type: boolean
      abi:
        type: array
        items:
          $ref: "#/definitions/CoBadgeAbi"
  CoBadgeAbi:
    type: object
    required:
      - name
      - abi
    properties:
      abi:
        type: string
      name:
        type: string
