swagger: "2.0"
info:
  version: "0.1"
paths:
definitions:
  Service:
    type: object
    required:
      - scope
    properties:
      description:
        type: string
      web_url:
        type: string
      app_ios:
        type: string
      app_android:
        type: string
      tos_url:
        type: string
      privacy_url:
        type: string
      address:
        type: string
      phone:
        type: string
      email:
        type: string
      pec:
        type: string
      scope:
        type: string
        x-extensible-enum:
          - NATIONAL
          - LOCAL
  Municipality:
    type: object
    required:
      - codiceRegione
      - codiceProvincia
      - denominazione
      - denominazioneInItaliano
      - denominazioneRegione
      - siglaProvincia
    properties:
      codiceRegione:
        type: string
      codiceProvincia:
        type: string
      denominazione:
        type: string
      denominazioneInItaliano:
        type: string
      denominazioneRegione:
        type: string
      siglaProvincia:
        type: string
  ServicesByScope:
    type: object
    required:
      - LOCAL
      - NATIONAL
    properties:
      LOCAL:
        type: array
      NATIONAL:
        type: array
