swagger: "2.0"
info:
  version: "0.2"
paths:
definitions:
  Service:
    type: object
    required:
      - scope
    properties:
      description:
        type: string
      web_url:
        type: string
      support_url:
        type: string
      app_ios:
        type: string
      app_android:
        type: string
      tos_url:
        type: string
      privacy_url:
        type: string
      address:
        type: string
      phone:
        type: string
      email:
        type: string
      pec:
        type: string
      cta:
        type: string
      token_name:
        type: string
      scope:
        type: string
        x-extensible-enum:
          - NATIONAL
          - LOCAL
  Municipality:
    type: object
    required:
      - codiceRegione
      - codiceProvincia
      - denominazione
      - denominazioneInItaliano
      - denominazioneRegione
      - siglaProvincia
    properties:
      codiceRegione:
        type: string
      codiceProvincia:
        type: string
      denominazione:
        type: string
      denominazioneInItaliano:
        type: string
      denominazioneRegione:
        type: string
      siglaProvincia:
        type: string
  ContextualHelp:
    type: object
    required:
      - version
      - it
      - en
    properties:
      version:
        type: number
      it:
        $ref: "#/definitions/ContextualHelpData"
      en:
        $ref: "#/definitions/ContextualHelpData"
  ContextualHelpData:
    type: object
    required:
      - idps
      - screens
    properties:
      idps:
        $ref: "#/definitions/IdpData"
      screens:
        $ref: "#/definitions/ScreensCHData"
  ScreensCHData:
    type: array
    items:
      $ref: "#/definitions/ScreenCHData"
  ScreenCHData:
    type: object
    required:
      - route_name
      - title
      - content
    properties:
      route_name:
        type: string
      title:
        type: string
      content:
        type: string
      faqs:
        type: array
        items:
          $ref: "#/definitions/Faq"
  IdpData:
    type: object
    properties:
      arubaid:
        $ref: "#/definitions/Idp"
      infocertid:
        $ref: "#/definitions/Idp"
      intesaid:
        $ref: "#/definitions/Idp"
      lepidaid:
        $ref: "#/definitions/Idp"
      namirialid:
        $ref: "#/definitions/Idp"
      posteid:
        $ref: "#/definitions/Idp"
      sielteid:
        $ref: "#/definitions/Idp"
      spiditalia:
        $ref: "#/definitions/Idp"
      timid:
        $ref: "#/definitions/Idp"
      cie:
        $ref: "#/definitions/Idp"
      test:
        $ref: "#/definitions/Idp"
  Idp:
    type: object
    required:
      - description
      - recover_password
      - phone
      - web_site
    properties:
      description:
        type: string
      email:
        type: string
      helpdesk_form:
        type: string
      phone:
        type: string
      phone_international:
        type: string
      web_site:
        type: string
      recover_username:
        type: string
      recover_password:
        type: string
      recover_emergency_code:
        type: string
  BonusesAvailable:
    type: array
    items:
      $ref: "#/definitions/BonusAvailable"
  BonusAvailable:
    type: object
    required:
      - id_type
      - is_active
      - valid_from
      - valid_to
      - it
      - en
    properties:
      id_type:
        type: number
      service_id:
        type: string
      is_active:
        type: boolean
      hidden:
        type: boolean
      cover:
        type: string
      sponsorship_cover:
        type: string
      sponsorship_description:
        type: string
      it:
        $ref: "#/definitions/BonusAvailableContent"
      en:
        $ref: "#/definitions/BonusAvailableContent"
      valid_from:
        $ref: "#/definitions/Timestamp"
      valid_to:
        $ref: "#/definitions/Timestamp"
      visibility:
        $ref: "#/definitions/BonusVisibility"
  BonusAvailableContent:
    type: object
    required:
      - name
      - title
      - subtitle
      - content
    properties:
      name:
        type: string
      title:
        type: string
      description:
        type: string
      subtitle:
        type: string
      content:
        type: string
      tos_url:
        type: string
      urls:
        type: array
        items:
          $ref: "#/definitions/BonusUrl"
  Timestamp:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/v10.2.3/openapi/definitions.yaml#/Timestamp"
  BonusVisibility:
    type: string
    x-extensible-enum:
      - visible
      - hidden
      - experimental
    example: visible
  BonusUrl:
    type: object
    required:
      - name
      - url
    properties:
      name:
        type: string
      url:
        type: string
  Faq:
    type: object
    required:
      - title
      - body
    properties:
      title:
        type: string
      body:
        type: string
  SpidIdps:
    type: object
    required:
      - items
    properties:
      items:
        type: array
        items:
          $ref: "#/definitions/SpidIdp"
  SpidIdp:
    type: object
    description: Entry used to generate the list of IDPs available to select on the login flow.
    required:
      - id
      - name
      - logo
      - profileUrl
    properties:
      id:
        type: string
      name:
        type: string
      logo:
        type: string
      profileUrl:
        type: string
      isTestIdp:
        type: boolean
  BackendStatus:
    type: object
    description: "A complex object representing multiple things: backend status, section status (a.k.a IO-App banners), remote config"
    required:
      - is_alive
      - message
      - sections
      - config
    properties:
      config:
        $ref: "#/definitions/Config"
      sections:
        $ref: "#/definitions/Sections"
      is_alive:
        type: boolean
      message:
        $ref: "#/definitions/BackendStatusMessage"
  BackendStatusMessage:
    type: object
    description: The message shown in IO-App when the backend is not alive
    required:
      - it-IT
      - en-EN
    properties:
      it-IT:
        type: string
      en-EN:
        type: string
  Sections:
    type: object
    description: The status of the app sections
    required:
      - bancomat
      - bancomatpay
      - cashback
      - cobadge
      - credit_card
      - digital_payments
      - email_validation
      - euCovidCert
      - ingress
      - login
      - messages
      - satispay
      - services
      - wallets
      - favourite_language
      - app_update_required
    properties:
      bancomat:
        $ref: "#/definitions/SectionStatus"
      bancomatpay:
        $ref: "#/definitions/SectionStatus"
      cashback:
        $ref: "#/definitions/SectionStatus"
      cobadge:
        $ref: "#/definitions/SectionStatus"
      credit_card:
        $ref: "#/definitions/SectionStatus"
      digital_payments:
        $ref: "#/definitions/SectionStatus"
      email_validation:
        $ref: "#/definitions/SectionStatus"
      euCovidCert:
        $ref: "#/definitions/SectionStatus"
      ingress:
        $ref: "#/definitions/SectionStatus"
      login:
        $ref: "#/definitions/SectionStatus"
      messages:
        $ref: "#/definitions/SectionStatus"
      satispay:
        $ref: "#/definitions/SectionStatus"
      services:
        $ref: "#/definitions/SectionStatus"
      wallets:
        $ref: "#/definitions/SectionStatus"
      favourite_language:
        $ref: "#/definitions/SectionStatus"
      app_update_required:
        $ref: "#/definitions/SectionStatus"
  SectionStatus:
    type: object
    description: The status of a specific app section
    required:
      - is_visible
      - level
      - message
    properties:
      badge:
        $ref: "#/definitions/BackendStatusMessage"
      web_url:
        $ref: "#/definitions/BackendStatusMessage"
      is_visible:
        type: boolean
      message:
        $ref: "#/definitions/BackendStatusMessage"
      level:
        type: string
        x-extensible-enum:
          - critical
          - warning
          - normal
  Config:
    type: object
    description: A remote config to enable/disable specific app features
    required:
      - bpd
      - bpd_ranking
      - bpd_ranking_v2
      - cgn_merchants_v2
      - assistanceTool
    properties:
      bpd:
        $ref: "#/definitions/BpdConfig"
      bpd_ranking:
        description: "bpd_ranking is legacy, don't use it anymore see https://www.pivotaltracker.com/story/show/176498731"
        type: boolean
      bpd_ranking_v2:
        type: boolean
      cgn_merchants_v2:
        type: boolean
      assistanceTool:
        $ref: "#/definitions/AssistanceToolConfig"
  BpdConfig:
    type: object
    description: A specific config for BPD bonus
    required:
      - enroll_bpd_after_add_payment_method
      - program_active
    properties:
      enroll_bpd_after_add_payment_method:
        description: "If true and the user is not enrolled to the cashback, the user is asked to activate the cashback after adding a new payment method"
        type: boolean
      program_active:
        description: "If true, the cashback program is active and all the related in app functionalities are enabled"
        type: boolean
  AssistanceToolConfig:
    type: object
    description: A specific config for Zendesk
    required:
      - tools
    properties:
      tools:
        type: string
        enum: [ none,zendesk,instabug,web ]
        description: "none: also used as default, the assistance is not visible; zendesk: the assistance is managed with zendesk; instabug: the assistance is managed with instabug; web: the assistance is managed with a web form;"

