swagger: "2.0"
info:
  version: "0.2"
paths:
definitions:
  Service:
    type: object
    required:
      - scope
    properties:
      description:
        type: string
      web_url:
        type: string
      support_url:
        type: string
      app_ios:
        type: string
      app_android:
        type: string
      tos_url:
        type: string
      privacy_url:
        type: string
      address:
        type: string
      phone:
        type: string
      email:
        type: string
      pec:
        type: string
      cta:
        type: string
      token_name:
        type: string
      scope:
        type: string
        x-extensible-enum:
          - NATIONAL
          - LOCAL
  Municipality:
    type: object
    required:
      - codiceRegione
      - codiceProvincia
      - denominazione
      - denominazioneInItaliano
      - denominazioneRegione
      - siglaProvincia
    properties:
      codiceRegione:
        type: string
      codiceProvincia:
        type: string
      denominazione:
        type: string
      denominazioneInItaliano:
        type: string
      denominazioneRegione:
        type: string
      siglaProvincia:
        type: string
  ContextualHelp:
    type: object
    required:
      - version
      - it
      - en
    properties:
      version:
        type: number
      it:
        $ref: "#/definitions/ContextualHelpData"
      en:
        $ref: "#/definitions/ContextualHelpData"
  ContextualHelpData:
    type: object
    required:
      - idps
      - screens
    properties:
      idps:
        $ref: "#/definitions/IdpData"
      screens:
        $ref: "#/definitions/ScreensCHData"
  ScreensCHData:
    type: array
    items:
      $ref: "#/definitions/ScreenCHData"
  ScreenCHData:
    type: object
    required:
      - route_name
      - title
      - content
    properties:
      route_name:
        type: string
      title:
        type: string
      content:
        type: string
      faqs:
        type: array
        items:
          $ref: "#/definitions/Faq"
  IdpData:
    type: object
    properties:
      arubaid:
        $ref: "#/definitions/Idp"
      infocertid:
        $ref: "#/definitions/Idp"
      intesaid:
        $ref: "#/definitions/Idp"
      lepidaid:
        $ref: "#/definitions/Idp"
      namirialid:
        $ref: "#/definitions/Idp"
      posteid:
        $ref: "#/definitions/Idp"
      sielteid:
        $ref: "#/definitions/Idp"
      spiditalia:
        $ref: "#/definitions/Idp"
      timid:
        $ref: "#/definitions/Idp"
      cie:
        $ref: "#/definitions/Idp"
      test:
        $ref: "#/definitions/Idp"
  Idp:
    type: object
    required:
      - description
      - recover_password
      - phone
      - web_site
    properties:
      description:
        type: string
      email:
        type: string
      helpdesk_form:
        type: string
      phone:
        type: string
      phone_international:
        type: string
      web_site:
        type: string
      recover_username:
        type: string
      recover_password:
        type: string
      recover_emergency_code:
        type: string
  BonusesAvailable:
    type: array
    items:
      $ref: "#/definitions/BonusAvailable"
  BonusAvailable:
    type: object
    required:
      - id_type
      - is_active
      - valid_from
      - valid_to
      - it
      - en
    properties:
      id_type:
        type: number
      service_id:
        type: string
      is_active:
        type: boolean
      hidden:
        type: boolean
      cover:
        type: string
      sponsorship_cover:
        type: string
      sponsorship_description:
        type: string
      it:
        $ref: "#/definitions/BonusAvailableContent"
      en:
        $ref: "#/definitions/BonusAvailableContent"
      valid_from:
        $ref: "#/definitions/Timestamp"
      valid_to:
        $ref: "#/definitions/Timestamp"
      visibility:
        $ref: "#/definitions/BonusVisibility"
  BonusAvailableContent:
    type: object
    required:
      - name
      - title
      - subtitle
      - content
    properties:
      name:
        type: string
      title:
        type: string
      description:
        type: string
      subtitle:
        type: string
      content:
        type: string
      tos_url:
        type: string
      urls:
        type: array
        items:
          $ref: "#/definitions/BonusUrl"
  Timestamp:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/v10.2.3/openapi/definitions.yaml#/Timestamp"
  BonusVisibility:
    type: string
    x-extensible-enum:
      - visible
      - hidden
      - experimental
    example: visible
  BonusUrl:
    type: object
    required:
      - name
      - url
    properties:
      name:
        type: string
      url:
        type: string
  Faq:
    type: object
    required:
      - title
      - body
    properties:
      title:
        type: string
      body:
        type: string
  SpidIdps:
    type: object
    required:
      - items
    properties:
      items:
        type: array
        items:
          $ref: "#/definitions/SpidIdp"
  SpidIdp:
    type: object
    description: Entry used to generate the list of IDPs available to select on the login flow.
    required:
      - id
      - name
      - logo
      - profileUrl
    properties:
      id:
        type: string
      name:
        type: string
      logo:
        type: string
      profileUrl:
        type: string
      isTestIdp:
        type: boolean
  BackendStatus:
    type: object
    description: "A complex object representing multiple things: backend status, section status (a.k.a IO-App banners), remote config"
    required:
      - is_alive
      - message
    properties:
      is_alive:
        type: boolean
      message:
        $ref: "#/definitions/BackendStatusMessage"
  BackendStatusMessage:
    type: object
    description: The message shown in IO-App when the backend is not alive
    required:
      - it-IT
      - en-EN
    properties:
      it-IT:
        type: string
      en-EN:
        type: string