defaults: &defaults
  working_directory: ~/repo

node_cache_key: &node_cache_key v1.1-dependencies-{{ checksum "yarn.lock" }}

defaults_js: &defaults_js
  <<: *defaults
  docker:
    - image: cimg/node:14.17.4

restore_node_cache: &restore_node_cache
  restore_cache:
    keys:
      - *node_cache_key

save_node_cache: &save_node_cache
  save_cache:
    paths:
      - node_modules
    key: *node_cache_key

install_node_modules: &install_node_modules
  run: yarn install --frozen-lockfile --no-progress --non-interactive --network-concurrency 1

version: 2
jobs:
  compile:
    <<: *defaults_js
    steps:
      - checkout
      - *restore_node_cache
      - *install_node_modules
      - *save_node_cache

  tests:
    <<: *defaults_js
    steps:
      - checkout
      - *restore_node_cache
      - *install_node_modules
      - run: yarn generate:all
      - run: yarn test

  lint:
    <<: *defaults_js
    steps:
      - checkout
      - *restore_node_cache
      - *install_node_modules
      - run: yarn lint

  # Check if all files respect the prettier rules
  check-prettier:
    <<: *defaults_js

    steps:
      - checkout
      - *restore_node_cache
      - *install_node_modules

      # Run linter
      - run: yarn prettier:check

  checks:
    <<: *defaults_js
    steps:
      - checkout
      - *restore_node_cache
      - *install_node_modules
      - run: yarn generate:all
      - run: yarn run_checks

  danger:
    <<: *defaults_js
    steps:
      - checkout
      - *restore_node_cache
      - *install_node_modules
      - run: '[ -z "$DANGER_GITHUB_API_TOKEN" ] || yarn danger ci'

workflows:
  version: 2
  build:
    jobs:
      - compile
      - tests
      - lint
      - check-prettier
      - checks
      - danger:
          filters:
            branches:
              ignore: master
