/**
 * Do not edit this file it is auto-generated by italia-utils / gen-api-models.
 * See https://github.com/teamdigitale/italia-utils
 */
/* tslint:disable */

import * as t from "io-ts";

// required attributes
const BonusAvailableContentR = t.interface({
  name: t.string,

  title: t.string,

  subtitle: t.string,

  content: t.string
});

// optional attributes
const BonusAvailableContentO = t.partial({
  tos_url: t.string
});

export const BonusAvailableContent = t.exact(
  t.intersection(
    [BonusAvailableContentR, BonusAvailableContentO],
    "BonusAvailableContent"
  )
);

export type BonusAvailableContent = t.TypeOf<typeof BonusAvailableContent>;
