/**
 * Do not edit this file it is auto-generated by italia-utils / gen-api-models.
 * See https://github.com/teamdigitale/italia-utils
 */
/* tslint:disable */

import * as t from "io-ts";
import { BonusAvailable } from "./BonusAvailable";

export type BonusesAvailable = t.TypeOf<typeof BonusesAvailable>;
export const BonusesAvailable = t.readonlyArray(
  BonusAvailable,
  "array of BonusAvailable"
);
