/**
 * Do not edit this file it is auto-generated by italia-utils / gen-api-models.
 * See https://github.com/teamdigitale/italia-utils
 */
/* tslint:disable */

import { BonusAvailableContent } from "./BonusAvailableContent";
import { Timestamp } from "./Timestamp";
import * as t from "io-ts";

// required attributes
const BonusAvailableR = t.interface({
  id_type: t.number,

  is_active: t.boolean,

  it: BonusAvailableContent,

  en: BonusAvailableContent,

  valid_from: Timestamp,

  valid_to: Timestamp
});

// optional attributes
const BonusAvailableO = t.partial({
  service_id: t.string,

  cover: t.string,

  sponsorship_cover: t.string,

  sponsorship_description: t.string
});

export const BonusAvailable = t.exact(
  t.intersection([BonusAvailableR, BonusAvailableO], "BonusAvailable")
);

export type BonusAvailable = t.TypeOf<typeof BonusAvailable>;
