/**
 * Do not edit this file it is auto-generated by italia-utils / gen-api-models.
 * See https://github.com/teamdigitale/italia-utils
 */
/* tslint:disable */

import * as t from "io-ts";

// required attributes
const ComuneR = t.interface({
  codiceRegione: t.string,

  codiceProvincia: t.string,

  denominazione: t.string,

  denominazioneInItaliano: t.string,

  denominazioneRegione: t.string
});

// optional attributes
const ComuneO = t.partial({});

export const Comune = t.exact(t.intersection([ComuneR, ComuneO], "Comune"));

export type Comune = t.TypeOf<typeof Comune>;
