/**
 * Do not edit this file it is auto-generated by italia-utils / gen-api-models.
 * See https://github.com/teamdigitale/italia-utils
 */
/* tslint:disable */

import { ContextualHelpData } from "./ContextualHelpData";
import * as t from "io-ts";

// required attributes
const ContextualHelpR = t.interface({
  version: t.number,

  it: ContextualHelpData,

  en: ContextualHelpData
});

// optional attributes
const ContextualHelpO = t.partial({});

export const ContextualHelp = t.exact(
  t.intersection([ContextualHelpR, ContextualHelpO], "ContextualHelp")
);

export type ContextualHelp = t.TypeOf<typeof ContextualHelp>;
