/**
 * Do not edit this file it is auto-generated by italia-utils / gen-api-models.
 * See https://github.com/teamdigitale/italia-utils
 */
/* tslint:disable */

import * as t from "io-ts";

// required attributes
const IdpR = t.interface({
  description: t.string,

  phone: t.string,

  web_site: t.string,

  recover_password: t.string
});

// optional attributes
const IdpO = t.partial({
  email: t.string,

  helpdesk_form: t.string,

  phone_international: t.string,

  recover_username: t.string,

  recover_emergency_code: t.string
});

export const Idp = t.exact(t.intersection([IdpR, IdpO], "Idp"));

export type Idp = t.TypeOf<typeof Idp>;
