/**
 * Do not edit this file it is auto-generated by italia-utils / gen-api-models.
 * See https://github.com/teamdigitale/italia-utils
 */
/* tslint:disable */

import { Idp } from "./Idp";
import * as t from "io-ts";

// required attributes
const IdpDataR = t.interface({});

// optional attributes
const IdpDataO = t.partial({
  arubaid: Idp,

  infocertid: Idp,

  intesaid: Idp,

  lepidaid: Idp,

  namirialid: Idp,

  posteid: Idp,

  sielteid: Idp,

  spiditalia: Idp,

  timid: Idp,

  cie: Idp,

  test: Idp
});

export const IdpData = t.exact(t.intersection([IdpDataR, IdpDataO], "IdpData"));

export type IdpData = t.TypeOf<typeof IdpData>;
