/**
 * Do not edit this file it is auto-generated by italia-utils / gen-api-models.
 * See https://github.com/teamdigitale/italia-utils
 */
/* tslint:disable */

import * as t from "io-ts";

// required attributes
const MunicipalityR = t.interface({
  codiceRegione: t.string,

  codiceProvincia: t.string,

  denominazione: t.string,

  denominazioneInItaliano: t.string,

  denominazioneRegione: t.string
});

// optional attributes
const MunicipalityO = t.partial({});

export const Municipality = t.exact(
  t.intersection([MunicipalityR, MunicipalityO], "Municipality")
);

export type Municipality = t.TypeOf<typeof Municipality>;
