/**
 * Do not edit this file it is auto-generated by italia-utils / gen-api-models.
 * See https://github.com/teamdigitale/italia-utils
 */
/* tslint:disable */

import * as t from "io-ts";

// required attributes
const ScreenCHDataR = t.interface({
  route_name: t.string,

  title: t.string,

  content: t.string
});

// optional attributes
const ScreenCHDataO = t.partial({});

export const ScreenCHData = t.exact(
  t.intersection([ScreenCHDataR, ScreenCHDataO], "ScreenCHData")
);

export type ScreenCHData = t.TypeOf<typeof ScreenCHData>;
