/**
 * Do not edit this file it is auto-generated by italia-utils / gen-api-models.
 * See https://github.com/teamdigitale/italia-utils
 */
/* tslint:disable */

import * as t from "io-ts";
import { ScreenCHData } from "./ScreenCHData";

export type ScreensCHData = t.TypeOf<typeof ScreensCHData>;
export const ScreensCHData = t.readonlyArray(
  ScreenCHData,
  "array of ScreenCHData"
);
