/**
 * Do not edit this file it is auto-generated by italia-utils / gen-api-models.
 * See https://github.com/teamdigitale/italia-utils
 */
/* tslint:disable */

import * as t from "io-ts";

// required attributes
const ServiceR = t.interface({
  scope: t.string
});

// optional attributes
const ServiceO = t.partial({
  description: t.string,

  web_url: t.string,

  app_ios: t.string,

  app_android: t.string,

  tos_url: t.string,

  privacy_url: t.string,

  address: t.string,

  phone: t.string,

  email: t.string,

  pec: t.string
});

export const Service = t.exact(t.intersection([ServiceR, ServiceO], "Service"));

export type Service = t.TypeOf<typeof Service>;
