/**
 * Do not edit this file it is auto-generated by italia-utils / gen-api-models.
 * See https://github.com/teamdigitale/italia-utils
 */
/* tslint:disable */

import * as t from "io-ts";

// required attributes
const ServicesByScopeR = t.interface({
  LOCAL: t.readonlyArray(t.string, "array of string"),

  NATIONAL: t.readonlyArray(t.string, "array of string")
});

// optional attributes
const ServicesByScopeO = t.partial({});

export const ServicesByScope = t.exact(
  t.intersection([ServicesByScopeR, ServicesByScopeO], "ServicesByScope")
);

export type ServicesByScope = t.TypeOf<typeof ServicesByScope>;
