on:
  pull_request

jobs:
  check-definitions:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          fetch-depth: 0  # Fetch all history for tags

      # Fetch the latest tag
      - name: Get latest tag
        id: get_latest_tag
        run: echo "LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV

      # Compare definitions using git diff
      - name: Compare API definitions
        id: compare_definitions
        run: |
          # Get the diff between the latest tag and the current branch
          git diff ${{ env.LATEST_TAG }} -- definitions.yml > definitions.diff

          # Check if the diff file is not empty
          if [ -s definitions.diff ]; then
            echo "::debug::Changes detected in API definitions"
            cat definitions.diff

            # Use awk to properly filter out x-extensible-enum changes
            cat definitions.diff | awk '
            BEGIN { in_extensible_enum = 0; removed_required = 0; }
            /x-extensible-enum:/ { in_extensible_enum = 1; next; }
            /^[^-]/ { if (in_extensible_enum == 1 && !match($0, /^[-+][ ]+- /)) in_extensible_enum = 0; }
            /^-[ ]+- / { 
              if (in_extensible_enum == 0) {
                removed_required++;
                print;
              }
            }
            END { exit removed_required > 0 ? 1 : 0; }
            ' > /dev/null
            
            if [ $? -eq 1 ]; then
              echo "::error::Required parameters removed in API definitions"
              echo "::group::Removed parameters"
              cat definitions.diff | awk '
              BEGIN { in_extensible_enum = 0; }
              /x-extensible-enum:/ { in_extensible_enum = 1; next; }
              /^[^-]/ { if (in_extensible_enum == 1 && !match($0, /^[-+][ ]+- /)) in_extensible_enum = 0; }
              /^-[ ]+- / { if (in_extensible_enum == 0) print; }
              '
              echo "::endgroup::"
              exit 1
            fi

            # Check for renamed required values (excluding x-extensible-enum)
            removed_required=$(cat definitions.diff | awk '
            BEGIN { in_extensible_enum = 0; removed_required = 0; }
            /x-extensible-enum:/ { in_extensible_enum = 1; next; }
            /^[^-]/ { if (in_extensible_enum == 1 && !match($0, /^[-+][ ]+- /)) in_extensible_enum = 0; }
            /^-[ ]+- / { if (in_extensible_enum == 0) removed_required++; }
            END { print removed_required; }
            ')
            
            added_required=$(grep -cE '^\+[ ]+- ' definitions.diff || echo "0")
            
            if [ "$removed_required" -gt 0 ] && [ "$added_required" -gt 0 ]; then
              echo "::error::Required parameters may have been renamed in API definitions"
              exit 1
            fi

            # Check for new required values and log warning if any
            if grep -qE '^\+[[:space:]]+-' definitions.diff; then
              echo "::warning::New required parameters introduced in API definitions"
              echo "::group::New parameters"
              grep -E '^\+[[:space:]]+-' definitions.diff || true
              echo "::endgroup::"
            fi

            # Check for type changes and log warning if any
            if grep -qE '^-.*type:' definitions.diff || grep -qE '^\+.*type:' definitions.diff; then
              echo "::warning::Type changes detected in API definitions"
              echo "::group::Type changes"
              grep -E '^-.*type:' definitions.diff || true
              grep -E '^\+.*type:' definitions.diff || true
              echo "::endgroup::"
            fi

            echo "::notice::Non-breaking changes detected in API definitions"
          else
            echo "::debug::No changes detected in API definitions"
          fi